# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import background_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1875, 1200)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("background-color rgb(170, 0, 0)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.video_frame = QtWidgets.QLabel(self.centralwidget)
        self.video_frame.setGeometry(QtCore.QRect(40, 60, 511, 371))
        self.video_frame.setText("")
        self.video_frame.setObjectName("video_frame")
        self.prediction_label = QtWidgets.QLabel(self.centralwidget)
        self.prediction_label.setGeometry(QtCore.QRect(60, 480, 600, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.prediction_label.setFont(font)
        self.prediction_label.setAlignment(QtCore.Qt.AlignCenter)
        self.prediction_label.setObjectName("prediction_label")
        self.timer_label = QtWidgets.QLabel(self.centralwidget)
        self.timer_label.setGeometry(QtCore.QRect(30, 520, 600, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.timer_label.setFont(font)
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.prediction_log_label = QtWidgets.QLabel(self.centralwidget)
        self.prediction_log_label.setGeometry(QtCore.QRect(630, 20, 301, 30))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.prediction_log_label.setFont(font)
        self.prediction_log_label.setObjectName("prediction_log_label")
        self.prediction_log_box = QtWidgets.QTextEdit(self.centralwidget)
        self.prediction_log_box.setGeometry(QtCore.QRect(709, 60, 271, 460))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.prediction_log_box.setFont(font)
        self.prediction_log_box.setReadOnly(True)
        self.prediction_log_box.setObjectName("prediction_log_box")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Goat Action App"))
        self.prediction_label.setText(_translate("MainWindow", "Predicted Action: Waiting..."))
        self.timer_label.setText(_translate("MainWindow", "Time since last prediction: 0s"))
        self.prediction_log_label.setText(_translate("MainWindow", "Prediction Log"))
