# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.video_frame = QtWidgets.QLabel(self.centralwidget)
        self.video_frame.setGeometry(QtCore.QRect(130, 140, 551, 411))
        self.video_frame.setText("")
        self.video_frame.setObjectName("video_frame")
        self.prediction_label = QtWidgets.QLabel(self.centralwidget)
        self.prediction_label.setGeometry(QtCore.QRect(100, 630, 600, 30))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(20)
        self.prediction_label.setFont(font)
        self.prediction_label.setAlignment(QtCore.Qt.AlignCenter)
        self.prediction_label.setObjectName("prediction_label")
        self.timer_label = QtWidgets.QLabel(self.centralwidget)
        self.timer_label.setGeometry(QtCore.QRect(100, 670, 600, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timer_label.setFont(font)
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.prediction_log_box = QtWidgets.QTextEdit(self.centralwidget)
        self.prediction_log_box.setGeometry(QtCore.QRect(840, 160, 331, 541))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.prediction_log_box.setFont(font)
        self.prediction_log_box.setReadOnly(True)
        self.prediction_log_box.setObjectName("prediction_log_box")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -1, 1231, 800))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-image:url(finalBg.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.video_frame.raise_()
        self.prediction_label.raise_()
        self.timer_label.raise_()
        self.prediction_log_box.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Goat Action App"))
        self.prediction_label.setText(_translate("MainWindow", "Predicted Action: Waiting..."))
        self.timer_label.setText(_translate("MainWindow", "Time since last prediction: 0s"))

